# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints_for_Basys3.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Video_timing_control_0_0/system_Video_timing_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_Video_timing_control_0_0 || ORIG_REF_NAME==system_Video_timing_control_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Video_Background_0_0/system_Video_Background_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_Video_Background_0_0 || ORIG_REF_NAME==system_Video_Background_0_0} -quiet] -quiet

# IP: bd/system/ip/system_RGB_Decoder_0_0/system_RGB_Decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_RGB_Decoder_0_0 || ORIG_REF_NAME==system_RGB_Decoder_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_0_100M_0/system_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==system_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_0_40M_0/system_rst_clk_wiz_0_40M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_0_40M_0 || ORIG_REF_NAME==system_rst_clk_wiz_0_40M_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ps2_0_0/system_axi_ps2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ps2_0_0 || ORIG_REF_NAME==system_axi_ps2_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_1/system_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_1 || ORIG_REF_NAME==system_microblaze_0_1} -quiet] -quiet

# IP: bd/system/ip/system_VGA_SQUAREDRAW_0_1/system_VGA_SQUAREDRAW_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_VGA_SQUAREDRAW_0_1 || ORIG_REF_NAME==system_VGA_SQUAREDRAW_0_1} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_1 || ORIG_REF_NAME==system_dlmb_v10_1} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_1 || ORIG_REF_NAME==system_ilmb_v10_1} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_1/system_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_1/system_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_1 || ORIG_REF_NAME==system_lmb_bram_1} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_periph_1/system_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_1 || ORIG_REF_NAME==system_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_intc_1/system_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_1 || ORIG_REF_NAME==system_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_xlconcat_0/system_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_xlconcat_0 || ORIG_REF_NAME==system_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
