#mouse
set_property PACKAGE_PIN C17 [get_ports {PS2_Clk_tri_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2_Clk_tri_io}]
set_property PULLUP true [get_ports PS2_Clk_tri_io]

set_property PACKAGE_PIN B17 [get_ports {PS2_Data_tri_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2_Data_tri_io}]
set_property PULLUP true [get_ports PS2_Data_tri_io]



#Vga
set_property PACKAGE_PIN G19 [get_ports {red_0[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[0]}]
set_property PACKAGE_PIN H19 [get_ports {red_0[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[1]}]
set_property PACKAGE_PIN J19 [get_ports {red_0[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[2]}]
set_property PACKAGE_PIN N19 [get_ports {red_0[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {red_0[3]}]
set_property PACKAGE_PIN N18 [get_ports {blue_0[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[0]}]
set_property PACKAGE_PIN L18 [get_ports {blue_0[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[1]}]
set_property PACKAGE_PIN K18 [get_ports {blue_0[2]}]				
    set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[2]}]
set_property PACKAGE_PIN J18 [get_ports {blue_0[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {blue_0[3]}]
set_property PACKAGE_PIN J17 [get_ports {green_0[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0[0]}]
set_property PACKAGE_PIN H17 [get_ports {green_0[1]}]				
    set_property IOSTANDARD LVCMOS33 [get_ports {green_0[1]}]
set_property PACKAGE_PIN G17 [get_ports {green_0[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0[2]}]
set_property PACKAGE_PIN D17 [get_ports {green_0[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {green_0[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync_out_0]						
	set_property IOSTANDARD LVCMOS33 [get_ports hsync_out_0]
set_property PACKAGE_PIN R19 [get_ports vsync_out_0]						
	set_property IOSTANDARD LVCMOS33 [get_ports vsync_out_0]